const missions = [
 {id:'sky',title:'Read the sky',desc:'Look up for two full minutes. Notice cloud shapes, movement, and where the light is coming from.',time:5,tag:'LOOK UP',icon:'☁'},
 {id:'three-greens',title:'Find three greens',desc:'Find three different shades of green. What makes each one look different?',time:5,tag:'NOTICE',icon:'❋'},
 {id:'listen',title:'A minute of listening',desc:'Stand still and identify three separate sounds without trying to name their source immediately.',time:5,tag:'LISTEN',icon:'♫'},
 {id:'texture',title:'Texture walk',desc:'Find five natural textures using only your eyes. Leave plants, bark, and fungi undisturbed.',time:10,tag:'OBSERVE',icon:'〰'},
 {id:'shadow',title:'Follow a shadow',desc:'Notice how a tree, wall, or railing makes a shadow. Return later and see what changed.',time:10,tag:'LIGHT',icon:'◒'},
 {id:'birds',title:'Birdwatch quietly',desc:'Watch birds from a respectful distance. Notice movement, calls, and how they travel.',time:10,tag:'WILDLIFE',icon:'⌁'},
 {id:'tiny-world',title:'Look closer',desc:'Observe a small patch of ground without disturbing it. What tiny patterns or movements can you spot?',time:10,tag:'DETAIL',icon:'⌕'},
 {id:'weather',title:'Make a weather note',desc:'Describe the temperature, wind, cloud cover, and the feeling of the air in your own words.',time:10,tag:'WEATHER',icon:'☼'},
 {id:'plant',title:'Meet a local plant',desc:'Observe a plant from the path. Note leaf shape, colour, and where it is growing. Do not taste it.',time:15,tag:'BOTANY',icon:'♧'},
 {id:'route',title:'Take a different route',desc:'With permission and in a familiar, safe area, take a different public path and notice what changes.',time:15,tag:'EXPLORE',icon:'↗'},
 {id:'sound-map',title:'Draw a sound map',desc:'On paper, mark where you hear sounds around you. Use symbols instead of words if you like.',time:15,tag:'LISTEN',icon:'◎'},
 {id:'sit',title:'Sit and notice',desc:'Spend fifteen quiet minutes outdoors. Record five things you noticed, not five things you photographed.',time:15,tag:'SLOW DOWN',icon:'◌'}
];
const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));
let completed = read('wildsense-completed', []); let notes = read('wildsense-notes', []); let activeFilter = 'all';
function renderMissions(){const grid=$('#missionGrid');grid.innerHTML='';missions.filter(m=>activeFilter==='all'||String(m.time)===activeFilter).forEach(m=>{const done=completed.includes(m.id);const card=document.createElement('article');card.className='mission-card';card.innerHTML=`<div class="mission-top"><span class="mission-icon" aria-hidden="true">${m.icon}</span><span class="duration">${m.time} MIN</span></div><h3>${m.title}</h3><p>${m.desc}</p><div class="mission-bottom"><span class="mission-tag">${m.tag}</span><button class="complete-btn ${done?'done':''}" data-id="${m.id}" aria-pressed="${done}">${done?'✓ Completed':'Mark complete +'}</button></div>`;grid.append(card);});$('#completedCount').textContent=completed.length;}
function renderNotes(){const host=$('#journalEntries');host.innerHTML='';$('#journalCount').textContent=notes.length;if(!notes.length){host.innerHTML='<p class="empty-note" style="font-size:11px;color:var(--muted);line-height:1.7">Your saved field notes will appear here.</p>';return;}notes.forEach(n=>{const el=document.createElement('article');el.className='note-entry';const title=document.createElement('h4');title.textContent=n.title;const body=document.createElement('p');body.textContent=n.body;const foot=document.createElement('footer');const date=document.createElement('span');date.textContent=new Date(n.created).toLocaleString();const del=document.createElement('button');del.className='delete-note';del.textContent='Delete';del.dataset.delete=n.id;foot.append(date,del);el.append(title,body,foot);host.append(el);});}
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.toggle('active',x===b));activeFilter=b.dataset.filter;renderMissions();}));
$('#missionGrid').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(!b)return;const id=b.dataset.id;completed=completed.includes(id)?completed.filter(x=>x!==id):[...completed,id];write('wildsense-completed',completed);renderMissions();});
$('#noteBody').addEventListener('input',()=>$('#charCount').textContent=`${$('#noteBody').value.length} / 1200`);
$('#journalForm').addEventListener('submit',e=>{e.preventDefault();notes.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),title:$('#noteTitle').value.trim(),body:$('#noteBody').value.trim(),created:new Date().toISOString()});write('wildsense-notes',notes);e.target.reset();$('#charCount').textContent='0 / 1200';$('#journalStatus').textContent='Field note saved in this browser.';renderNotes();});
$('#journalEntries').addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b)return;notes=notes.filter(n=>n.id!==b.dataset.delete);write('wildsense-notes',notes);renderNotes();});
$('#exportNotes').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),notes,completedMissions:completed},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='wildsense-field-journal.json';a.click();URL.revokeObjectURL(url);$('#journalStatus').textContent='Export prepared.';});
$('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('wildsense-theme',document.body.classList.contains('dark')?'dark':'light');});if(localStorage.getItem('wildsense-theme')==='dark')document.body.classList.add('dark');
function addMessage(role,text){const el=document.createElement('div');el.className=`message ${role}`;if(role==='assistant'){const label=document.createElement('span');label.className='message-label';label.textContent='WILDSENSE';el.append(label);}el.append(document.createTextNode(text));$('#chatMessages').append(el);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight;return el;}
async function checkAI(){try{const r=await fetch('/api/status');const data=await r.json();$('#aiStatus').textContent=data.available?`Connected to local Ollama · ${data.model}`:data.ollama?'Ollama is running, but model ${data.model} is not installed.': 'Local Ollama not detected. See README for setup.';}catch{$('#aiStatus').textContent='Start this website with start.bat to enable the local AI connection.';}}
async function sendChat(text){const prompt=text.trim();if(!prompt)return;addMessage('user',prompt);$('#chatInput').value='';const waiting=addMessage('assistant','Thinking on your local model…');try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Local AI request failed.');waiting.lastChild.textContent=data.response||'No response returned.';}catch(err){waiting.lastChild.textContent=`${err.message} Check that Ollama is running and the model is installed.`;}$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight;}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();sendChat($('#chatInput').value);});$$('.suggestions button').forEach(b=>b.addEventListener('click',()=>sendChat(b.dataset.prompt)));renderMissions();renderNotes();checkAI();
